version: '3'
services:
  nginx:
    container_name: nginx
    build: ./.docker/nginx
    ports:
      - 80:80
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: 'Asia/Tokyo'
      PORT: '8080'
    volumes:
      - ./:/go/src/app
    expose:
      - 8080
    tty: true
    command: go run main.go
