version: '3'
services:
  app-go:
    container_name: app-go
    build:
      context: ./.docker/app
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./app/:/go/src/app
    tty: true
